# Generated by Django 4.1.4 on 2023-04-06 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0002_alter_menu_booking_time"),
    ]

    operations = [
        migrations.RemoveField(model_name="menu", name="booking_time",),
        migrations.AddField(
            model_name="booking",
            name="booking_time",
            field=models.DateTimeField(default=None),
        ),
    ]
