# Generated by Django 4.1.4 on 2023-04-06 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0003_remove_menu_booking_time_booking_booking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_time",
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
