# Generated by Django 4.1.4 on 2023-04-06 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("restaurant", "0004_alter_booking_booking_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_time",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 4, 6, 13, 56, 54, 179672)
            ),
            preserve_default=False,
        ),
    ]
